<a href="https://colab.research.google.com/github/Aysuliu/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [32]:
import pandas as pd

In [33]:
print(pd.__version__)

2.2.2

In [34]:
mydataset = {
    'cars': ["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Ford", "BMW"],
    'counts': [3, 7, 2, 8, 1, 9, 3]
}
print(mydataset)
print("===============")

df = pd.DataFrame(mydataset)

print(df)

{'cars': ['BMW', 'Volvo', 'Ford', 'Tesla', 'Ferrari', 'Ford', 'BMW'], 'counts': [3, 7, 2, 8, 1, 9, 3]}
===============
      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [35]:
df.head() #default 5 rows

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1

In [36]:
df.tail(-1) #ohiridan boshlab korsatadi

      cars  counts
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [37]:
df.shape

(7, 2)

In [38]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [39]:
df.dtypes

cars      object
counts     int64
dtype: object

In [40]:
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [41]:
df.describe() #numerical columns only statistics

         counts
count  7.000000
mean   4.714286
std    3.199702
min    1.000000
25%    2.500000
50%    3.000000
75%    7.500000
max    9.000000

In [42]:
df.describe(include="all") #numerical columns only

       cars    counts
count     7  7.000000
unique    5       NaN
top     BMW       NaN
freq      2       NaN
mean    NaN  4.714286
std     NaN  3.199702
min     NaN  1.000000
25%     NaN  2.500000
50%     NaN  3.000000
75%     NaN  7.500000
max     NaN  9.000000

In [43]:
df.iloc[1:4] # select row w its column

    cars  counts
1  Volvo       7
2   Ford       2
3  Tesla       8

In [44]:
df.loc[:, "counts"]
df.loc[2, "cars"]
df.loc[2:5, "cars"]

2       Ford
3      Tesla
4    Ferrari
5       Ford
Name: cars, dtype: object

In [45]:
df[df["counts"]>3]

df[df["cars"] == "Tesla"]

    cars  counts
3  Tesla       8

In [46]:
df.mean(numeric_only=True)
df["counts"].mean()

np.float64(4.714285714285714)

In [47]:
df.sum()

cars      BMWVolvoFordTeslaFerrariFordBMW
counts                                 33
dtype: object

In [48]:
df.max()

cars      Volvo
counts        9
dtype: object

In [49]:
df.median(numeric_only=True) #middle value

counts    3.0
dtype: float64

In [50]:
df.count()

cars      7
counts    7
dtype: int64

In [51]:
df.std(numeric_only=True) #standard deviation

counts    3.199702
dtype: float64

In [52]:
data_with_missing = {
    "cars": ["BMW", "Volvo", None, "Tesla", "Ferrari", None, "Ford"],
    "counts": [3, 7, None, 8, 1, 9, None],
}

df_missing = pd.DataFrame(data_with_missing)
df_missing

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     None     NaN
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0
6     Ford     NaN

In [53]:
df_missing.isnull().sum() #boolean check

cars      2
counts    2
dtype: int64

In [54]:
df_missing.dropna(how="all") #drop missing values
df_missing.dropna(axis=1)
df_missing.dropna(subset=["cars"])

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0
6     Ford     NaN

In [55]:
df_missing.fillna({"cars":"unknown", "counts":0})

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2  unknown     0.0
3    Tesla     8.0
4  Ferrari     1.0
5  unknown     9.0
6     Ford     0.0

In [56]:
df = pd.read_csv("Titanic-Dataset.csv")
df.head()
df.tail()

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
1304,1305,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1305,1306,39.0,108.9000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1306,1307,38.5,7.2500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1307,1308,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1308,1309,28.0,22.3583,0,1,0,0,0,0,0,...,0,0,0,3,0,0,0.0,0,0,0

In [57]:
df.to_excel("output.xlsx")

In [58]:
#Series => 1D arrays
cars = pd.Series(["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Ford", "BMW"])
print(cars)

0        BMW
1      Volvo
2       Ford
3      Tesla
4    Ferrari
5       Ford
6        BMW
dtype: object

In [59]:
# 2D Series
cars_series = data_with_missing['cars']
print(cars_series)

['BMW', 'Volvo', None, 'Tesla', 'Ferrari', None, 'Ford']